/*
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * OpenAPI spec version: 2024.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * ExternalIdObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-01T19:29:10.951410897Z[GMT]")

public class ExternalIdObject {
  @SerializedName("isrc")
  private String isrc = null;

  @SerializedName("ean")
  private String ean = null;

  @SerializedName("upc")
  private String upc = null;

  public ExternalIdObject isrc(String isrc) {
    this.isrc = isrc;
    return this;
  }

   /**
   * [International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code) 
   * @return isrc
  **/
  @Schema(description = "[International Standard Recording Code](http://en.wikipedia.org/wiki/International_Standard_Recording_Code) ")
  public String getIsrc() {
    return isrc;
  }

  public void setIsrc(String isrc) {
    this.isrc = isrc;
  }

  public ExternalIdObject ean(String ean) {
    this.ean = ean;
    return this;
  }

   /**
   * [International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29) 
   * @return ean
  **/
  @Schema(description = "[International Article Number](http://en.wikipedia.org/wiki/International_Article_Number_%28EAN%29) ")
  public String getEan() {
    return ean;
  }

  public void setEan(String ean) {
    this.ean = ean;
  }

  public ExternalIdObject upc(String upc) {
    this.upc = upc;
    return this;
  }

   /**
   * [Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code) 
   * @return upc
  **/
  @Schema(description = "[Universal Product Code](http://en.wikipedia.org/wiki/Universal_Product_Code) ")
  public String getUpc() {
    return upc;
  }

  public void setUpc(String upc) {
    this.upc = upc;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ExternalIdObject externalIdObject = (ExternalIdObject) o;
    return Objects.equals(this.isrc, externalIdObject.isrc) &&
        Objects.equals(this.ean, externalIdObject.ean) &&
        Objects.equals(this.upc, externalIdObject.upc);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isrc, ean, upc);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExternalIdObject {\n");
    
    sb.append("    isrc: ").append(toIndentedString(isrc)).append("\n");
    sb.append("    ean: ").append(toIndentedString(ean)).append("\n");
    sb.append("    upc: ").append(toIndentedString(upc)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
