/*
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * OpenAPI spec version: 2024.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.ImageObject;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
/**
 * PrivateUserObject
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2024-05-01T19:29:10.951410897Z[GMT]")

public class PrivateUserObject {
  @SerializedName("country")
  private String country = null;

  @SerializedName("display_name")
  private String displayName = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("explicit_content")
  private AllOfPrivateUserObjectExplicitContent explicitContent = null;

  @SerializedName("external_urls")
  private AllOfPrivateUserObjectExternalUrls externalUrls = null;

  @SerializedName("followers")
  private AllOfPrivateUserObjectFollowers followers = null;

  @SerializedName("href")
  private String href = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("images")
  private List<ImageObject> images = null;

  @SerializedName("product")
  private String product = null;

  @SerializedName("type")
  private String type = null;

  @SerializedName("uri")
  private String uri = null;

  public PrivateUserObject country(String country) {
    this.country = country;
    return this;
  }

   /**
   * The country of the user, as set in the user&#x27;s account profile. An [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ 
   * @return country
  **/
  @Schema(description = "The country of the user, as set in the user's account profile. An [ISO 3166-1 alpha-2 country code](http://en.wikipedia.org/wiki/ISO_3166-1_alpha-2). _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ ")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public PrivateUserObject displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * The name displayed on the user&#x27;s profile. &#x60;null&#x60; if not available. 
   * @return displayName
  **/
  @Schema(description = "The name displayed on the user's profile. `null` if not available. ")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public PrivateUserObject email(String email) {
    this.email = email;
    return this;
  }

   /**
   * The user&#x27;s email address, as entered by the user when creating their account. _**Important!** This email address is unverified; there is no proof that it actually belongs to the user._ _This field is only available when the current user has granted access to the [user-read-email](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ 
   * @return email
  **/
  @Schema(description = "The user's email address, as entered by the user when creating their account. _**Important!** This email address is unverified; there is no proof that it actually belongs to the user._ _This field is only available when the current user has granted access to the [user-read-email](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ ")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public PrivateUserObject explicitContent(AllOfPrivateUserObjectExplicitContent explicitContent) {
    this.explicitContent = explicitContent;
    return this;
  }

   /**
   * The user&#x27;s explicit content settings. _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ 
   * @return explicitContent
  **/
  @Schema(description = "The user's explicit content settings. _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ ")
  public AllOfPrivateUserObjectExplicitContent getExplicitContent() {
    return explicitContent;
  }

  public void setExplicitContent(AllOfPrivateUserObjectExplicitContent explicitContent) {
    this.explicitContent = explicitContent;
  }

  public PrivateUserObject externalUrls(AllOfPrivateUserObjectExternalUrls externalUrls) {
    this.externalUrls = externalUrls;
    return this;
  }

   /**
   * Known external URLs for this user.
   * @return externalUrls
  **/
  @Schema(description = "Known external URLs for this user.")
  public AllOfPrivateUserObjectExternalUrls getExternalUrls() {
    return externalUrls;
  }

  public void setExternalUrls(AllOfPrivateUserObjectExternalUrls externalUrls) {
    this.externalUrls = externalUrls;
  }

  public PrivateUserObject followers(AllOfPrivateUserObjectFollowers followers) {
    this.followers = followers;
    return this;
  }

   /**
   * Information about the followers of the user.
   * @return followers
  **/
  @Schema(description = "Information about the followers of the user.")
  public AllOfPrivateUserObjectFollowers getFollowers() {
    return followers;
  }

  public void setFollowers(AllOfPrivateUserObjectFollowers followers) {
    this.followers = followers;
  }

  public PrivateUserObject href(String href) {
    this.href = href;
    return this;
  }

   /**
   * A link to the Web API endpoint for this user. 
   * @return href
  **/
  @Schema(description = "A link to the Web API endpoint for this user. ")
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public PrivateUserObject id(String id) {
    this.id = id;
    return this;
  }

   /**
   * The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for the user. 
   * @return id
  **/
  @Schema(description = "The [Spotify user ID](/documentation/web-api/concepts/spotify-uris-ids) for the user. ")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public PrivateUserObject images(List<ImageObject> images) {
    this.images = images;
    return this;
  }

  public PrivateUserObject addImagesItem(ImageObject imagesItem) {
    if (this.images == null) {
      this.images = new ArrayList<ImageObject>();
    }
    this.images.add(imagesItem);
    return this;
  }

   /**
   * The user&#x27;s profile image.
   * @return images
  **/
  @Schema(description = "The user's profile image.")
  public List<ImageObject> getImages() {
    return images;
  }

  public void setImages(List<ImageObject> images) {
    this.images = images;
  }

  public PrivateUserObject product(String product) {
    this.product = product;
    return this;
  }

   /**
   * The user&#x27;s Spotify subscription level: \&quot;premium\&quot;, \&quot;free\&quot;, etc. (The subscription level \&quot;open\&quot; can be considered the same as \&quot;free\&quot;.) _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ 
   * @return product
  **/
  @Schema(description = "The user's Spotify subscription level: \"premium\", \"free\", etc. (The subscription level \"open\" can be considered the same as \"free\".) _This field is only available when the current user has granted access to the [user-read-private](/documentation/web-api/concepts/scopes/#list-of-scopes) scope._ ")
  public String getProduct() {
    return product;
  }

  public void setProduct(String product) {
    this.product = product;
  }

  public PrivateUserObject type(String type) {
    this.type = type;
    return this;
  }

   /**
   * The object type: \&quot;user\&quot; 
   * @return type
  **/
  @Schema(description = "The object type: \"user\" ")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public PrivateUserObject uri(String uri) {
    this.uri = uri;
    return this;
  }

   /**
   * The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the user. 
   * @return uri
  **/
  @Schema(description = "The [Spotify URI](/documentation/web-api/concepts/spotify-uris-ids) for the user. ")
  public String getUri() {
    return uri;
  }

  public void setUri(String uri) {
    this.uri = uri;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PrivateUserObject privateUserObject = (PrivateUserObject) o;
    return Objects.equals(this.country, privateUserObject.country) &&
        Objects.equals(this.displayName, privateUserObject.displayName) &&
        Objects.equals(this.email, privateUserObject.email) &&
        Objects.equals(this.explicitContent, privateUserObject.explicitContent) &&
        Objects.equals(this.externalUrls, privateUserObject.externalUrls) &&
        Objects.equals(this.followers, privateUserObject.followers) &&
        Objects.equals(this.href, privateUserObject.href) &&
        Objects.equals(this.id, privateUserObject.id) &&
        Objects.equals(this.images, privateUserObject.images) &&
        Objects.equals(this.product, privateUserObject.product) &&
        Objects.equals(this.type, privateUserObject.type) &&
        Objects.equals(this.uri, privateUserObject.uri);
  }

  @Override
  public int hashCode() {
    return Objects.hash(country, displayName, email, explicitContent, externalUrls, followers, href, id, images, product, type, uri);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PrivateUserObject {\n");
    
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    explicitContent: ").append(toIndentedString(explicitContent)).append("\n");
    sb.append("    externalUrls: ").append(toIndentedString(externalUrls)).append("\n");
    sb.append("    followers: ").append(toIndentedString(followers)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    images: ").append(toIndentedString(images)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    uri: ").append(toIndentedString(uri)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
