/*
 * Spotify Web API with fixes and improvements from sonallux
 * You can use Spotify's Web API to discover music and podcasts, manage your Spotify library, control audio playback, and much more. Browse our available Web API endpoints using the sidebar at left, or via the navigation bar on top of this page on smaller screens.  In order to make successful Web API requests your app will need a valid access token. One can be obtained through <a href=\"https://developer.spotify.com/documentation/general/guides/authorization-guide/\">OAuth 2.0</a>.  The base URI for all Web API requests is `https://api.spotify.com/v1`.  Need help? See our <a href=\"https://developer.spotify.com/documentation/web-api/guides/\">Web API guides</a> for more information, or visit the <a href=\"https://community.spotify.com/t5/Spotify-for-Developers/bd-p/Spotify_Developer\">Spotify for Developers community forum</a> to ask questions and connect with other developers. 
 *
 * OpenAPI spec version: 2024.3.3
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.CurrentlyPlayingContextObject;
import io.swagger.client.model.CurrentlyPlayingObject;
import io.swagger.client.model.CursorPagingPlayHistoryObject;
import io.swagger.client.model.InlineResponse20014;
import io.swagger.client.model.InlineResponse401;
import io.swagger.client.model.QueueObject;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PlayerApi
 */
@Ignore
public class PlayerApiTest {

    private final PlayerApi api = new PlayerApi();

    /**
     * Add Item to Playback Queue 
     *
     * Add an item to the end of the user&#x27;s current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addToQueueTest() throws Exception {
        String uri = null;
        String deviceId = null;
        api.addToQueue(uri, deviceId);

        // TODO: test validations
    }
    /**
     * Get Available Devices 
     *
     * Get information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAUsersAvailableDevicesTest() throws Exception {
        InlineResponse20014 response = api.getAUsersAvailableDevices();

        // TODO: test validations
    }
    /**
     * Get Playback State 
     *
     * Get information about the user’s current playback state, including track or episode, progress, and active device. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getInformationAboutTheUsersCurrentPlaybackTest() throws Exception {
        String market = null;
        String additionalTypes = null;
        CurrentlyPlayingContextObject response = api.getInformationAboutTheUsersCurrentPlayback(market, additionalTypes);

        // TODO: test validations
    }
    /**
     * Get the User&#x27;s Queue 
     *
     * Get the list of objects that make up the user&#x27;s queue. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getQueueTest() throws Exception {
        QueueObject response = api.getQueue();

        // TODO: test validations
    }
    /**
     * Get Recently Played Tracks 
     *
     * Get tracks from the current user&#x27;s recently played tracks. _**Note**: Currently doesn&#x27;t support podcast episodes._ 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getRecentlyPlayedTest() throws Exception {
        Integer limit = null;
        Integer after = null;
        Integer before = null;
        CursorPagingPlayHistoryObject response = api.getRecentlyPlayed(limit, after, before);

        // TODO: test validations
    }
    /**
     * Get Currently Playing Track 
     *
     * Get the object currently being played on the user&#x27;s Spotify account. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTheUsersCurrentlyPlayingTrackTest() throws Exception {
        String market = null;
        String additionalTypes = null;
        CurrentlyPlayingObject response = api.getTheUsersCurrentlyPlayingTrack(market, additionalTypes);

        // TODO: test validations
    }
    /**
     * Pause Playback 
     *
     * Pause playback on the user&#x27;s account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void pauseAUsersPlaybackTest() throws Exception {
        String deviceId = null;
        api.pauseAUsersPlayback(deviceId);

        // TODO: test validations
    }
    /**
     * Seek To Position 
     *
     * Seeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void seekToPositionInCurrentlyPlayingTrackTest() throws Exception {
        Integer positionMs = null;
        String deviceId = null;
        api.seekToPositionInCurrentlyPlayingTrack(positionMs, deviceId);

        // TODO: test validations
    }
    /**
     * Set Repeat Mode 
     *
     * Set the repeat mode for the user&#x27;s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setRepeatModeOnUsersPlaybackTest() throws Exception {
        String state = null;
        String deviceId = null;
        api.setRepeatModeOnUsersPlayback(state, deviceId);

        // TODO: test validations
    }
    /**
     * Set Playback Volume 
     *
     * Set the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setVolumeForUsersPlaybackTest() throws Exception {
        Integer volumePercent = null;
        String deviceId = null;
        api.setVolumeForUsersPlayback(volumePercent, deviceId);

        // TODO: test validations
    }
    /**
     * Skip To Next 
     *
     * Skips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void skipUsersPlaybackToNextTrackTest() throws Exception {
        String deviceId = null;
        api.skipUsersPlaybackToNextTrack(deviceId);

        // TODO: test validations
    }
    /**
     * Skip To Previous 
     *
     * Skips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void skipUsersPlaybackToPreviousTrackTest() throws Exception {
        String deviceId = null;
        api.skipUsersPlaybackToPreviousTrack(deviceId);

        // TODO: test validations
    }
    /**
     * Start/Resume Playback 
     *
     * Start a new context or resume current playback on the user&#x27;s active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void startAUsersPlaybackTest() throws Exception {
        Map<String, Object> body = null;
        String deviceId = null;
        api.startAUsersPlayback(body, deviceId);

        // TODO: test validations
    }
    /**
     * Toggle Playback Shuffle 
     *
     * Toggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void toggleShuffleForUsersPlaybackTest() throws Exception {
        Boolean state = null;
        String deviceId = null;
        api.toggleShuffleForUsersPlayback(state, deviceId);

        // TODO: test validations
    }
    /**
     * Transfer Playback 
     *
     * Transfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints. 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void transferAUsersPlaybackTest() throws Exception {
        Map<String, Object> body = null;
        api.transferAUsersPlayback(body);

        // TODO: test validations
    }
}
